"""
Django settings for config project.

Generated by 'django-admin startproject'.
"""

import os
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# --------------------------------------------------
# Security
# --------------------------------------------------

# Use Railway/environment secret in production.
# The fallback keeps the existing local project working.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-jeo@d@&wv1tkr^n6c7_1(*yd4a#ur5r4(qf%@=6g+1gn)at@v6"
)

# Local development defaults to True.
# Railway deployment can set DJANGO_DEBUG=False.
DEBUG = os.environ.get(
    "DJANGO_DEBUG",
    "True"
).lower() == "true"


# Allowed hosts for local development.
ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "192.168.1.179",
]


# Railway provides the public domain through this variable
# when available.
railway_domain = os.environ.get("RAILWAY_PUBLIC_DOMAIN")

if railway_domain:
    ALLOWED_HOSTS.append(railway_domain)


# You can also manually provide additional hosts through:
# DJANGO_ALLOWED_HOSTS=example.com,another.example.com
extra_allowed_hosts = os.environ.get(
    "DJANGO_ALLOWED_HOSTS",
    ""
).strip()

if extra_allowed_hosts:
    ALLOWED_HOSTS.extend(
        host.strip()
        for host in extra_allowed_hosts.split(",")
        if host.strip()
    )


# --------------------------------------------------
# Application definition
# --------------------------------------------------

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Django REST Framework
    "rest_framework",

    # FitTrackAI app
    "fitness",
]


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "config.urls"


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = "config.wsgi.application"


# --------------------------------------------------
# Database
# --------------------------------------------------
#
# LOCAL:
# Uses the XAMPP MariaDB/MySQL database.
#
# RAILWAY:
# Uses Railway's MySQL environment variables.
#
# Railway provides:
# MYSQLDATABASE
# MYSQLUSER
# MYSQLPASSWORD
# MYSQLHOST
# MYSQLPORT
#

railway_mysql_host = os.environ.get("MYSQLHOST")

if railway_mysql_host:
    # ----------------------------------------------
    # Railway MySQL
    # ----------------------------------------------
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": os.environ.get(
                "MYSQLDATABASE",
                os.environ.get("MYSQL_DATABASE", "")
            ),
            "USER": os.environ.get(
                "MYSQLUSER",
                "root"
            ),
            "PASSWORD": os.environ.get(
                "MYSQLPASSWORD",
                ""
            ),
            "HOST": railway_mysql_host,
            "PORT": os.environ.get(
                "MYSQLPORT",
                "3306"
            ),
            "OPTIONS": {
                "init_command": (
                    "SET sql_mode='STRICT_TRANS_TABLES'"
                ),
            },
        }
    }

else:
    # ----------------------------------------------
    # Local XAMPP MariaDB/MySQL
    # ----------------------------------------------
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": "fittrackai_db",
            "USER": "root",
            "PASSWORD": "",
            "HOST": "127.0.0.1",
            "PORT": "3306",

            # Enable MariaDB Strict Mode
            "OPTIONS": {
                "init_command": (
                    "SET sql_mode='STRICT_TRANS_TABLES'"
                ),
            },
        }
    }


# --------------------------------------------------
# Password validation
# --------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]


# --------------------------------------------------
# Internationalization
# --------------------------------------------------

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Manila"

USE_I18N = True

USE_TZ = True


# --------------------------------------------------
# Static files
# --------------------------------------------------

STATIC_URL = "static/"


# --------------------------------------------------
# Email
# --------------------------------------------------

EMAIL_BACKEND = (
    "django.core.mail.backends.console.EmailBackend"
)


# --------------------------------------------------
# Default primary key field type
# --------------------------------------------------

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"